Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@mjkim1019 
depromeet
/
fairer-Android
Public
Fork your own copy of depromeet/fairer-Android
Code
Issues
1
Pull requests
Discussions
Actions
Projects
Wiki
Security
Insights
Settings
fairer-Android/.github/workflows/android.yml
@wjdwns
wjdwns Fix/main view (#126)
…
Latest commit d9f784c on Aug 22, 2022
 History
 2 contributors
@wjdwns@onemask
41 lines (32 sloc)  895 Bytes

name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run ktlint
      run: ./gradlew ktlintCheck
